#ifndef CONTROLLER_NOTEDURATION_H_
#define CONTROLLER_NOTEDURATION_H_

enum NoteDuration {
    HALF_NOTE,
    BEAT,
    EIGHTH,
    SIXTEENTH,
    HALF_TRIPLET,
    BEAT_TRIPLET,
    EIGHTH_TRIPLET,
    SIXTEENTH_TRIPLET
};

#endif